import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { loadDefault, loadNamespace, makeCtx, makePi, makeSessionManager, contentEntry, messageEntry, PC, PI, runHandlers, toolResultEntry, waitUntil } from "./harness.mjs";

/**
 * Handoff scaffolding tests: the continuation prompt follows the conversation language
 * (`auto`), an explicit `lang` config wins, carried-over continuation prompts are replaced
 * by an omission marker in the verbatim replay slice, and the `runHandoff` call sites are pinned
 * through a stubbed summarizer plus a `newSession` mock (review round 5, F3/F5).
 */

const tmp = await mkdtemp(path.join(os.tmpdir(), "pi-handoff-"));
let failures = 0;
function check(label, value) {
	console.log(`${value ? "OK  " : "FAIL"} ${label}`);
	if (!value) failures += 1;
}
const configPath = path.join(tmp, ".agents/memory/project-context.json");
const readConfig = () => readFile(configPath, "utf8").then((raw) => JSON.parse(raw)).catch(() => undefined);
/** Verbatim reply for the stubbed summarizer: English template headings, localized by the code. */
const PINNED_SUMMARY = ["## Goal", "- 做完了。", "", "## Critical Context", "- pinned summary body."].join("\n");

try {
	await mkdir(path.join(tmp, ".agents/memory"), { recursive: true });

	const handoff = await loadNamespace(`${PC}/handoff.ts`);

	console.log("=== detectHandoffLanguage ===");
	check("Chinese user text picks zh", handoff.detectHandoffLanguage(["那做了呗，统一一下", "把记忆也改成 append-only 的模型，别残留隐患"]) === "zh");
	check("English user text picks en", handoff.detectHandoffLanguage(["fix the bug", "add tests for the replay slice"]) === "en");
	check("short Chinese sample falls back to en", handoff.detectHandoffLanguage(["B C A", "好"]) === "en");
	check(
		"Chinese prose dominates code-heavy samples",
		handoff.detectHandoffLanguage(["这段代码 memory.jsonl 的 fold 逻辑要按 mtime 判断外部编辑，不要每次重扫", "const value = await readJson(file);"]) === "zh",
	);

	console.log("\n=== buildHandoffPrompt ===");
	const base = {
		percent: 16,
		keptTokens: 20_000,
		guardWaiting: false,
		summaryWithIndex: "## Goal\n- 收尾。\n\n<read-files>\na.ts\n</read-files>",
		previousSessionId: "01a0a58e-7ef4-7763-95f3-5bcf04fdc388",
		previousSessionFile: "/home/user/.pi/agent/sessions/x.jsonl",
	};
	const zh = handoff.buildHandoffPrompt({ ...base, language: "zh" });
	check("zh preamble carries the percent", zh.startsWith("本会话接手上一会话（其上下文窗口已用 16%）。"));
	check("zh headings", zh.includes("## 交接摘要") && zh.includes("## 上一会话信息"));
	check("zh details", zh.includes("- 上一会话 id：01a0a58e") && zh.includes("- 原始记录（JSONL）：/home/user/.pi/agent/sessions/x.jsonl"));
	check("zh closing", zh.trimEnd().endsWith("从上次中断处继续。"));
	check("zh has no English scaffolding", !zh.includes("## Handoff Summary") && !zh.includes("Continue the task from where it left off."));

	const en = handoff.buildHandoffPrompt({ ...base, language: "en" });
	check(
		"en keeps the legacy shape",
		en.startsWith("This session continues work handed off from a previous session (16% of its context window had been used).") &&
			en.includes("## Handoff Summary") &&
			en.includes("## Previous session details") &&
			en.trimEnd().endsWith("Continue the task from where it left off."),
	);

	const zhSummaryOnly = handoff.buildHandoffPrompt({ ...base, language: "zh", keptTokens: 0 });
	check("zh summary-only carry line", zhSummaryOnly.includes("上一会话只留下下面的交接摘要"));

	const zhGuarded = handoff.buildHandoffPrompt({ ...base, language: "zh", guardWaiting: true, pendingQuestion: "选 1 还是 2？" });
	check("zh guarded prompt carries the question", zhGuarded.includes("## 待用户回答的问题") && zhGuarded.includes("选 1 还是 2？"));
	check("zh guarded prompt waits for the user", zhGuarded.trimEnd().endsWith("任务停在上面的问题上。不要替用户选选项或开工，等用户回答。"));
	check("guarded prompt notes the open decision", zhGuarded.includes("这个决定仍未决"));

	const noFile = handoff.buildHandoffPrompt({ ...base, language: "zh", previousSessionFile: undefined });
	check("no transcript line without a session file", !noFile.includes("原始记录"));
	check("zh unknown percent is localized", handoff.buildHandoffPrompt({ ...base, language: "zh", percent: null }).includes("已用 阈值以上）。"));
	check(
		"en unknown percent keeps the legacy wording",
		handoff.buildHandoffPrompt({ ...base, language: "en", percent: null }).startsWith("This session continues work handed off from a previous session (over threshold"),
	);

	console.log("\n=== isHandoffPromptText ===");
	// Literal text generated by the pre-language build (kept 01a0a58e's prompt shape).
	const legacy = [
		"This session continues work handed off from a previous session (16% of its context window had been used).",
		"The handoff summary below covers the earlier part of that session; its most recent messages were carried over verbatim.",
		"Verify the current state of files with tools before re-applying changes, and do not redo completed work.",
		"",
		"## Handoff Summary",
		"",
		"## Goal\n- 收尾。",
		"",
		"## Previous session details",
		"- Previous session id: 01a0a58e-7ef4-7763-95f3-5bcf04fdc388",
		"Continue the task from where it left off.",
	].join("\n");
	check("recognizes a generated zh prompt", handoff.isHandoffPromptText(zh));
	check("recognizes a generated en prompt", handoff.isHandoffPromptText(en));
	check("recognizes a legacy English prompt", handoff.isHandoffPromptText(legacy));
	check("ordinary user message is not a prompt", !handoff.isHandoffPromptText("那做了呗，统一一下"));
	check("assistant report is not a prompt", !handoff.isHandoffPromptText("## Goal\n- 收尾。"));
	check("a quote prefixed by the user is not a prompt", !handoff.isHandoffPromptText(`补，但是当前会话怎么出现了：\n${en}`));
	check("a quote with appended text is not a prompt", !handoff.isHandoffPromptText(`${en}\n\n顺便问一下，这个 HANDOFF.md 为什么没人看？`));
	check("a legacy quote with appended text is not a prompt", !handoff.isHandoffPromptText(`${legacy}\n另外把 v0.1.3 也处理一下`));
	check("headings alone are not a prompt", !handoff.isHandoffPromptText("## Handoff Summary\n\n没什么。"));
	check("empty text is not a prompt", !handoff.isHandoffPromptText("   "));

	console.log("\n=== replayMessagesFor ===");
	const entries = [
		messageEntry("e1", "user", "那做了呗，统一一下", "2026-09-16T00:41:39.660Z"),
		messageEntry("e2", "user", legacy, "2026-09-16T00:41:39.844Z"),
		messageEntry("e3", "assistant", "按交接要求先核对当前实际状态。", "2026-09-16T00:41:44.876Z"),
		contentEntry("e3a", "assistant", [{ type: "toolCall", id: "tc9", name: "bash", arguments: { command: "git log" } }], "2026-09-16T00:41:45.000Z"),
		toolResultEntry("e4", "tc9", "=== HEAD ===\ne4d48c4", "2026-09-16T00:41:57.106Z"),
		messageEntry("e5", "user", zh, "2026-09-16T00:41:58.000Z"),
	];
	const kept = handoff.replayMessagesFor(entries);
	check("stale continuation prompts are replaced by the marker", kept.filter((message) => message.content?.[0]?.text === handoff.REPLAY_MARKER).length === 2);
	check("the raw prompt text never reaches the replay", !kept.some((message) => (message.content?.[0]?.text ?? "").includes("## Handoff Summary")));
	// e1, e3, the tool call and its paired result stay; the two prompts become markers.
	check("real conversation stays in the slice", kept.filter((message) => message.content?.[0]?.text !== handoff.REPLAY_MARKER).length === 4);

	console.log("\n=== replay block shape ===");
	// A slice that starts on a carried-over prompt used to be kept as-is (user-first); replacing
	// it must not make the block open with an assistant message, which some providers reject.
	const cutSlice = [
		messageEntry("c0", "user", legacy, "2026-09-16T00:41:00.000Z"),
		messageEntry("c1", "assistant", "按交接要求先核对当前实际状态。", "2026-09-16T00:41:01.000Z"),
		messageEntry("c2", "user", "真实用户问题", "2026-09-16T00:41:02.000Z"),
	];
	const replayed = handoff.replayMessagesFor(cutSlice);
	check("the replay block still opens with a user message", replayed[0]?.role === "user");
	check("the opening message is the omission marker", replayed[0]?.content?.[0]?.text === handoff.REPLAY_MARKER);
	check("later real messages are untouched", replayed[2]?.content?.[0]?.text === "真实用户问题");
	const plain = handoff.replayMessagesFor([messageEntry("q0", "user", "普通消息", "2026-09-16T00:42:00.000Z"), messageEntry("q1", "assistant", "普通回答", "2026-09-16T00:42:01.000Z")]);
	check("no prompt means no marker", !plain.some((message) => message.content?.[0]?.text === handoff.REPLAY_MARKER));

	console.log("\n=== buildHandoffDocument ===");
	const docParts = {
		previousSessionId: "01a0a7a9-7235-7763-95f3-5bdc121f5eff",
		projectRoot: "/tmp/proj",
		sessionLogRel: ".agents/memory/session-logs/01a0a7a9/session.md",
		summaryWithIndex: "## Goal\n- 收尾。",
		createdAt: "2026-09-16T00:50:03.901Z",
	};
	const zhDoc = handoff.buildHandoffDocument({ ...docParts, language: "zh" });
	check("zh document header", zhDoc.startsWith("# pi 会话 01a0a7a9-7235-7763-95f3-5bdc121f5eff 的交接文档") && zhDoc.includes("- 生成时间：2026-09-16T00:50:03.901Z"));
	check("zh document fields", zhDoc.includes("- 项目：/tmp/proj") && zhDoc.includes("- 会话日志：.agents/memory/session-logs/01a0a7a9/session.md") && zhDoc.includes("- 会话索引：.agents/memory/session-logs/INDEX.md"));
	check("document carries the summary", zhDoc.trimEnd().endsWith("- 收尾。"));
	const enDoc = handoff.buildHandoffDocument({ ...docParts, language: "en" });
	check(
		"en document keeps the legacy header",
		enDoc.startsWith("# Handoff from pi session 01a0a7a9-7235-7763-95f3-5bdc121f5eff") && enDoc.includes("- Created: 2026-09-16T00:50:03.901Z"),
	);

	console.log("\n=== resolveLanguage (auto) ===");
	const msg = (role, text) => ({ role, content: [{ type: "text", text }] });
	const englishTask = [msg("user", "please implement item 2 and run the tests"), msg("assistant", "done")];
	check(
		"injected prompts do not poison the language decision",
		handoff.resolveLanguage([msg("user", zh), ...englishTask], "auto") === "en",
	);
	check(
		"the user's own Chinese decides zh",
		handoff.resolveLanguage([msg("user", "那做了呗，统一一下"), ...englishTask], "auto") === "zh",
	);
	check(
		"recent messages win over older ones",
		handoff.resolveLanguage([msg("user", "这段中文很长很长，说明一开始说的是中文。"), ...[1, 2, 3, 4, 5, 6, 7, 8].map((index) => msg("user", `english follow-up number ${index}`))], "auto") === "en",
	);
	check(
		"a tiny recent sample falls back to the whole session",
		handoff.resolveLanguage([msg("user", "中文背景说明，包含足够多的汉字。"), msg("user", "ok")], "auto") === "zh",
	);
	check("explicit config wins", handoff.resolveLanguage(englishTask, "zh") === "zh" && handoff.resolveLanguage([msg("user", "中文")], "en") === "en");
	check(
		"the omission marker is ignored by language sampling",
		handoff.resolveLanguage([msg("user", zh), msg("user", handoff.REPLAY_MARKER)], "auto") === "zh",
	);
	// Pins the runHandoff wiring: the decision samples the raw carried slice, so the prompt sitting
	// on the cut point stays visible to the carry-forward rule (a marker-substituted slice hides it).
	check(
		"the raw slice feeds the language decision",
		handoff.resolveLanguage(handoff.languageMessagesFor([msg("user", "older english turn")], [msg("user", zh), msg("user", "ok")]), "auto") === "zh",
	);
	check("a short Chinese reply keeps zh", handoff.resolveLanguage([msg("user", zh), msg("user", "继续")], "auto") === "zh");
	check(
		"a single-character reply carries the language forward",
		handoff.resolveLanguage([msg("user", zh), msg("user", "好")], "auto") === "zh",
	);
	check(
		"an ASCII reply carries the language forward",
		handoff.resolveLanguage([msg("user", zh), msg("user", "ok")], "auto") === "zh" &&
			handoff.resolveLanguage([msg("user", en), msg("user", "ok")], "auto") === "en",
	);
	check(
		"substantive English still flips to en",
		handoff.resolveLanguage([msg("user", zh), msg("user", "please implement item 2 and run the tests")], "auto") === "en",
	);

	console.log("\n=== summary headings ===");
	// Verbatim headings from a real deepseek-flash summary captured during the TUI auto-handoff run
	// (2026-09-16): pi's EXACT-format prompt keeps the English template headings even when the
	// focus line asks for Chinese, so the fixed set is mapped deterministically.
	const realSummary = [
		"## Goal",
		"- 记录本次真机验证的相关要点（目标与检查点）。",
		"",
		"## Constraints & Preferences",
		"- 一切确认语句均使用一句话中文，且不要提问。",
		"",
		"## Progress",
		"### Done",
		"- [x] 记录第一条：本次真机验证的目标是 TUI 自动交臂。",
		"",
		"### In Progress",
		"- [ ] (无明确进行中的任务)",
		"",
		"### Blocked",
		"- (无)",
		"",
		"## Key Decisions",
		"- **概括方式统一**：两文件均以一句话中文概括。",
		"",
		"## Next Steps",
		"1. 等待用户后续指令。",
		"",
		"## Critical Context",
		"- 两次读取的 tool result 均有大段内容被截断。",
	].join("\n");
	const localized = handoff.localizeSummaryHeadings(realSummary, "zh");
	check(
		"zh maps every template heading",
		["## 目标", "## 约束与偏好", "## 进展", "### 已完成", "### 进行中", "### 受阻", "## 关键决策", "## 下一步", "## 关键上下文"].every((heading) =>
			localized.includes(heading),
		),
	);
	check(
		"zh leaves no template heading behind",
		!["## Goal", "## Constraints & Preferences", "## Progress", "### Done", "### In Progress", "### Blocked", "## Key Decisions", "## Next Steps", "## Critical Context"].some(
			(heading) => localized.includes(heading),
		),
	);
	check("zh keeps the summary body", localized.includes("- [x] 记录第一条：本次真机验证的目标是 TUI 自动交臂。"));
	check("a heading word inside a line is not rewritten", handoff.localizeSummaryHeadings("- 参见 ## Goal 一节", "zh") === "- 参见 ## Goal 一节");
	check("a heading inside a code fence is not rewritten", handoff.localizeSummaryHeadings("```md\n## Goal\n```\n## Progress", "zh") === "```md\n## Goal\n```\n## 进展");
	check(
		"fences close with their own marker",
		handoff.localizeSummaryHeadings("~~~\n## Goal\n~~~\n## Goal", "zh") === "~~~\n## Goal\n~~~\n## 目标",
	);
	check("an indented heading keeps its indent", handoff.localizeSummaryHeadings("  ## Goal\n- x", "zh") === "  ## 目标\n- x");
	check("already localized headings are left alone", handoff.localizeSummaryHeadings("## 目标\n- x", "zh") === "## 目标\n- x");
	check(
		"en maps the localized headings back",
		handoff.localizeSummaryHeadings("## 目标\n### 已完成\n- x", "en") === "## Goal\n### Done\n- x",
	);
	check(
		"en also maps the variants real models produced",
		handoff.localizeSummaryHeadings("## 进度\n### 阻塞", "en") === "## Progress\n### Blocked",
	);

	console.log("\n=== config parsing ===");
	const parseConfig = async (raw) => {
		await writeFile(configPath, JSON.stringify(raw));
		return (await loadNamespace(`${PC}/config.ts`)).getConfig(tmp);
	};
	const flat = await parseConfig({ handoffLanguage: "zh" });
	check("flat handoffLanguage loads", flat.handoffLanguage === "zh");
	const flatWins = await parseConfig({ handoffLanguage: "zh", handoff: { language: "en" } });
	check("flat value beats the nested legacy key", flatWins.handoffLanguage === "zh");
	const nestedInvalid = await parseConfig({ handoff: { language: "fr" } });
	check("invalid nested value falls back to auto", nestedInvalid.handoffLanguage === "auto");
	const nested = await parseConfig({ handoff: { language: "en" } });
	check("nested legacy handoff.language loads", nested.handoffLanguage === "en");
	const invalid = await parseConfig({ handoffLanguage: "fr" });
	check("unknown language falls back to auto", invalid.handoffLanguage === "auto");
	const defaults = await parseConfig({});
	check("defaults to auto", defaults.handoffLanguage === "auto");
	// Legacy global file (`~/.pi/agent/auto-handoff.json`); redirect the agent dir instead.
	const agentDir = path.join(tmp, "agentdir");
	await mkdir(agentDir, { recursive: true });
	await writeFile(path.join(agentDir, "auto-handoff.json"), JSON.stringify({ language: "en" }));
	const previousAgentDir = process.env.PI_CODING_AGENT_DIR;
	process.env.PI_CODING_AGENT_DIR = agentDir;
	try {
		await writeFile(configPath, JSON.stringify({}));
		const globalLegacy = await (await loadNamespace(`${PC}/config.ts`)).getConfig(tmp);
		check("global legacy language loads", globalLegacy.handoffLanguage === "en");
	} finally {
		if (previousAgentDir === undefined) delete process.env.PI_CODING_AGENT_DIR;
		else process.env.PI_CODING_AGENT_DIR = previousAgentDir;
	}

	console.log("\n=== /auto-handoff lang ===");
	await writeFile(configPath, JSON.stringify({}));
	const pi = makePi({ cwd: tmp });
	await (await loadDefault(`${PC}/index.ts`))(pi);
	const ctx = makeCtx(tmp, { sessionManager: makeSessionManager([], "handoff-lang") });
	await runHandlers(pi, "session_start", ctx);
	const command = pi.commands.get("auto-handoff");
	check("command registered", command !== undefined);
	await command.handler("lang zh", ctx);
	check("lang zh persists", (await readConfig())?.handoffLanguage === "zh");
	await command.handler("lang fr", ctx);
	check("invalid language warns and leaves the config", (await readConfig())?.handoffLanguage === "zh" && String(ctx.notifications.at(-1)?.[0] ?? "").includes("lang auto|zh|en"));
	await command.handler("lang auto", ctx);
	check("lang auto persists", (await readConfig())?.handoffLanguage === "auto");
	await command.handler("language zh", ctx);
	check("the language alias works", (await readConfig())?.handoffLanguage === "zh");
	await command.handler("lang EN", ctx);
	check("the language value is case-insensitive", (await readConfig())?.handoffLanguage === "en");
	await command.handler("lang", ctx);
	check("a missing value warns and leaves the config", (await readConfig())?.handoffLanguage === "en" && String(ctx.notifications.at(-1)?.[0] ?? "").includes("lang auto|zh|en"));
	await command.handler("lang auto", ctx);
	await command.handler("status", ctx);
	check("status reports the language", String(ctx.notifications.at(-1)?.[0] ?? "").includes("lang auto"));

	console.log("\n=== /auto-handoff now (nothing to hand off) ===");
	// A no-op handoff must explain itself: both bail-outs used to return without any notify.
	await writeFile(configPath, JSON.stringify({ handoffKeepTokens: 50 }));
	const quiet = makePi({ cwd: tmp });
	await (await loadDefault(`${PC}/index.ts`))(quiet);
	const emptyCtx = makeCtx(tmp, { sessionManager: makeSessionManager([], "handoff-empty") });
	await runHandlers(quiet, "session_start", emptyCtx);
	await quiet.commands.get("auto-handoff").handler("now", emptyCtx);
	check(
		"an empty session reports the skip",
		String(emptyCtx.notifications.at(-1)?.[0] ?? "").includes("no messages yet") &&
			String(emptyCtx.notifications.at(-1)?.[1] ?? "") === "warning",
	);

	const short = makeSessionManager(
		[
			messageEntry("m1", "user", "你好", "2026-09-16T00:00:00.000Z"),
			messageEntry("m2", "assistant", "你好", "2026-09-16T00:00:01.000Z"),
		],
		"handoff-short",
	);
	const shortCtx = makeCtx(tmp, { sessionManager: short });
	await runHandlers(quiet, "session_start", shortCtx);
	await quiet.commands.get("auto-handoff").handler("now", shortCtx);
	check(
		"a session inside the keep window reports the skip",
		String(shortCtx.notifications.at(-1)?.[0] ?? "").includes("nothing older than the recent window") &&
			String(shortCtx.notifications.at(-1)?.[1] ?? "") === "warning",
	);

	console.log("\n=== auto trigger backoff ===");
	// maybeTrigger fires on every settle; a skip that keeps firing would warn on each turn.
	// The adaptive threshold needs the session to hold more than `handoffTargetTokens` of
	// conversation, so the mocked context carries real bulk instead of a huge baseline.
	await writeFile(configPath, JSON.stringify({ handoffEnabled: true, handoffKeepTokens: 50, handoffTargetTokens: 8_000, autoConsolidate: false }));
	const auto = makePi({ cwd: tmp });
	await (await loadDefault(`${PC}/index.ts`))(auto);
	const filler = "documentation line repeated to give the session real context weight. ".repeat(700);
	// buildContextEntries walks the parent chain from the leaf, so the mock entries must link.
	const firstTurn = messageEntry("a1", "user", filler, "2026-09-16T00:00:00.000Z");
	const secondTurn = messageEntry("a2", "assistant", "已收到。", "2026-09-16T00:00:01.000Z");
	secondTurn.parentId = firstTurn.id;
	const autoCtx = makeCtx(tmp, {
		sessionManager: makeSessionManager([firstTurn, secondTurn], "handoff-auto"),
		mode: "tui",
		getContextUsage: () => ({ tokens: 200_000, percent: 20, contextWindow: 1_000_000 }),
	});
	await runHandlers(auto, "session_start", autoCtx);
	await runHandlers(auto, "agent_settled", autoCtx);
	await waitUntil(() => auto.sentMessages.includes("/auto-handoff force-auto"));
	check("the threshold triggers the scheduled handoff", auto.sentMessages.includes("/auto-handoff force-auto"));
	await auto.commands.get("auto-handoff").handler("force-auto", autoCtx);
	check("the scheduled handoff explains the skip", String(autoCtx.notifications.at(-1)?.[0] ?? "").includes("nothing older than the recent window"));
	await runHandlers(auto, "agent_settled", autoCtx);
	// Negative assertion: a pending setTimeout(0) trigger runs before this timer, so one flush is enough.
	await new Promise((resolve) => setTimeout(resolve, 0));
	check("a skipped auto handoff backs off instead of retrying every settle", auto.sentMessages.length === 1);

	console.log("\n=== replay block shape (mid-turn cut) ===");
	// The keep-budget cut can land inside a turn, so the slice opens on an assistant message, which
	// Anthropic/Gemini routes reject; it gets a user-role stand-in for the summarized prefix.
	const turnEntries = [
		contentEntry("k0", "user", [{ type: "text", text: "原始请求" }], "2026-09-16T00:43:00.000Z"),
		contentEntry(
			"k1",
			"assistant",
			[{ type: "text", text: "先看实现。" }, { type: "toolCall", id: "tc1", name: "bash", arguments: { command: "cat x" } }],
			"2026-09-16T00:43:01.000Z",
		),
	];
	const midTurn = handoff.replayMessagesFor([turnEntries[1], toolResultEntry("k2", "tc1", "输出", "2026-09-16T00:43:02.000Z")]);
	check("a mid-turn slice opens with the split-turn marker", midTurn[0]?.role === "user" && midTurn[0]?.content?.[0]?.text === handoff.SPLIT_TURN_MARKER);
	check("the tool call and its result stay paired after the marker", midTurn[1]?.content?.[1]?.type === "toolCall" && midTurn[2]?.content?.[0]?.text === "输出");
	check("a slice that already opens with a user message gets no split marker", handoff.replayMessagesFor([turnEntries[0]])[0]?.content?.[0]?.text === "原始请求");
	// A cut can land on a summary entry that the replay filters out, exposing a tool result whose
	// call lives in the summarized prefix: the orphan is dropped and the block still opens user-first.
	const filteredInputs = [
		contentEntry("s0", "branchSummary", [{ type: "text", text: "分支摘要" }], "2026-09-16T00:44:00.000Z"),
		contentEntry("s1", "toolResult", [{ type: "text", text: "结果" }], "2026-09-16T00:44:01.000Z"),
		contentEntry("s2", "assistant", [{ type: "text", text: "继续。" }], "2026-09-16T00:44:02.000Z"),
	];
	const orphanInbox = [];
	const filteredHead = handoff.replayMessagesFor(filteredInputs, orphanInbox);
	check(
		"a filtered summary entry drops the orphan result and opens user-first",
		filteredHead[0]?.role === "user" &&
			filteredHead[0]?.content?.[0]?.text === handoff.SPLIT_TURN_MARKER &&
			filteredHead.map((message) => message.role).join(",") === "user,assistant",
	);
	check("the dropped orphan result is handed back for the summary", orphanInbox.length === 1 && orphanInbox[0]?.content?.[0]?.text === "结果");
	check(
		"a slice holding only orphan results replays nothing",
		handoff.replayMessagesFor([contentEntry("s3", "toolResult", [{ type: "text", text: "结果" }], "2026-09-16T00:44:03.000Z")]).length === 0,
	);
	// An orphan in the middle of a slice (its call is not part of it) is dropped as well, while a
	// result whose call is kept stays paired.
	const midOrphans = [];
	const midSlice = handoff.replayMessagesFor(
		[
			contentEntry("q0", "user", [{ type: "text", text: "用户" }], "2026-09-16T00:45:00.000Z"),
			toolResultEntry("q1", "gone", "孤儿结果", "2026-09-16T00:45:01.000Z"),
			contentEntry("q2", "assistant", [{ type: "toolCall", id: "keep1", name: "bash", arguments: {} }], "2026-09-16T00:45:02.000Z"),
			toolResultEntry("q3", "keep1", "配对结果", "2026-09-16T00:45:03.000Z"),
		],
		midOrphans,
	);
	check(
		"a mid-slice orphan is dropped and handed back",
		midOrphans.length === 1 && midOrphans[0]?.content?.[0]?.text === "孤儿结果" && !JSON.stringify(midSlice).includes("孤儿结果") && JSON.stringify(midSlice).includes("配对结果"),
	);
	const bashEntry = {
		type: "message",
		id: "s9",
		parentId: null,
		timestamp: "2026-09-16T00:44:04.000Z",
		message: { role: "bashExecution", command: "ls", output: "", timestamp: Date.parse("2026-09-16T00:44:04.000Z") },
	};
	check("a bash turn start needs no split marker", handoff.replayMessagesFor([bashEntry])[0]?.role === "bashExecution");

	console.log("\n=== runHandoff call sites ===");
	// Pins what the pure-function tests cannot: which slice feeds the summarizer, which language
	// directive it gets, that the reply's headings are localized before they reach the prompt, and
	// that the replay is the post-cut slice. The summarizer lives in pi's SDK, so it is shadowed by
	// a stub that re-exports the real module. (The raw-vs-marker distinction inside the carried slice
	// is behaviourally equivalent here, so it is deliberately not asserted; see analysis R2.)
	const stubCalls = [];
	globalThis.__handoffStub = (messages, meta) => {
		stubCalls.push({ messages, ...meta });
		return { text: PINNED_SUMMARY, usage: undefined };
	};
	const sdkStub = path.join(tmp, "sdk-stub.mjs");
	await writeFile(
		sdkStub,
		`export * from ${JSON.stringify(path.join(PI, "dist", "index.js"))};\n` +
			"export async function generateSummaryWithUsage(messages, model, reserve, apiKey, headers, signal, focus, previousSummary, thinking) {\n" +
			"\treturn globalThis.__handoffStub(messages, { focus, previousSummary, thinking });\n" +
			"}\n",
	);
	const stubAlias = { "@earendil-works/pi-coding-agent": sdkStub };

	await writeFile(configPath, JSON.stringify({ handoffEnabled: true, handoffKeepTokens: 50, handoffTargetTokens: 8_000, autoConsolidate: false }));
	const toolOutput = "tool output line that was read earlier in this turn. ".repeat(200);
	const pinEntries = [
		contentEntry("p1", "user", [{ type: "text", text: "Please make the memory journal append-only and add tests for it." }], "2026-09-16T00:50:00.000Z"),
		contentEntry(
			"p2",
			"assistant",
			[{ type: "text", text: "Reading the current implementation first." }, { type: "toolCall", id: "pc1", name: "bash", arguments: { command: "cat extensions/project-context/project-state.ts" } }],
			"2026-09-16T00:50:01.000Z",
			"p1",
		),
		toolResultEntry("p3", "pc1", toolOutput, "2026-09-16T00:50:02.000Z", "p2"),
		contentEntry("p4", "assistant", [{ type: "text", text: "看完了，我来改。" }], "2026-09-16T00:50:03.000Z", "p3"),
		contentEntry("p5", "user", [{ type: "text", text: "好，动手。" }], "2026-09-16T00:50:04.000Z", "p4"),
	];
	const captureNewSession = (store) => async (options) => {
		const replacement = makeSessionManager([], "handoff-pin-next");
		await options.setup(replacement);
		store.replay = replacement.entries.slice();
		const replacementCtx = makeCtx(tmp, { sessionManager: replacement });
		store.notifications = replacementCtx.notifications;
		replacementCtx.sendUserMessage = (text) => {
			store.prompt = text;
		};
		await options.withSession(replacementCtx);
		return { cancelled: false };
	};
	const captured = { replay: [], prompt: undefined };
	const pinPi = makePi({ cwd: tmp });
	await (await loadDefault(`${PC}/index.ts`, stubAlias))(pinPi);
	const pinCtx = makeCtx(tmp, {
		sessionManager: makeSessionManager(pinEntries, "handoff-pin"),
		getContextUsage: () => ({ tokens: 200_000, percent: 20, contextWindow: 1_000_000 }),
		modelRegistry: {
			hasConfiguredAuth: () => true,
			find: () => undefined,
			getApiKeyAndHeaders: async () => ({ ok: true, apiKey: "test-key" }),
			complete: async () => {
				throw new Error("the stub must serve the summary");
			},
		},
	});
	pinCtx.newSession = captureNewSession(captured);
	await runHandlers(pinPi, "session_start", pinCtx);
	await pinPi.commands.get("auto-handoff").handler("now", pinCtx);

	check("the forced handoff switches sessions", captured.replay.length > 0 && captured.prompt !== undefined);
	check(
		"the summarizer receives the cut-off turn prefix",
		stubCalls.length === 1 && stubCalls[0].messages.some((message) => JSON.stringify(message.content ?? "").includes("tool output line")),
	);
	check("the carried slice is not re-summarized", !stubCalls[0]?.messages.some((message) => JSON.stringify(message.content ?? "").includes("我来改")));
	check("the summary call carries the conversation language", String(stubCalls[0]?.focus ?? "").includes("Simplified Chinese"));
	check("the model's headings are localized before they reach the prompt", String(captured.prompt).includes("## 目标") && !String(captured.prompt).includes("## Goal"));
	check("the prompt carries the summary body and the previous session", String(captured.prompt).includes("- 做完了。") && String(captured.prompt).includes("handoff-pin"));
	check(
		"the replay is the post-cut slice, opening user-first",
		captured.replay[0]?.role === "user" &&
			captured.replay[0]?.content?.[0]?.text === handoff.SPLIT_TURN_MARKER &&
			captured.replay.map((message) => message.role).join(",") === "user,assistant,user",
	);
	check("the dropped tool output never enters the replay", !JSON.stringify(captured.replay).includes("tool output line"));
	check("the continuation is announced", String(captured.notifications?.at(-1)?.[0] ?? "").includes("continued in a fresh session"));
	const handoffDoc = await readFile(path.join(tmp, ".agents/memory/HANDOFF.md"), "utf8").catch(() => "");
	check("the archived handoff document carries the localized summary", handoffDoc.includes("## 目标") && handoffDoc.includes("- 做完了。"));

	// An orphan result (its call left in the summary prefix) must not vanish: it leaves the replay
	// but its content is folded into the summary input.
	const orphanEntries = [
		contentEntry("o1", "user", [{ type: "text", text: "先看实现，再改。" }], "2026-09-16T01:00:00.000Z"),
		contentEntry(
			"o2",
			"assistant",
			[{ type: "text", text: "读取实现。" }, { type: "toolCall", id: "oc1", name: "bash", arguments: { command: "cat x" } }],
			"2026-09-16T01:00:01.000Z",
			"o1",
		),
		{ type: "branch_summary", id: "o3", parentId: "o2", timestamp: "2026-09-16T01:00:02.000Z", summary: "分支摘要 branch summary filler. ".repeat(60) },
		toolResultEntry("o4", "oc1", "孤儿结果 ORPHAN_SECRET", "2026-09-16T01:00:03.000Z", "o3"),
		contentEntry("o5", "assistant", [{ type: "text", text: "继续改。" }], "2026-09-16T01:00:04.000Z", "o4"),
		contentEntry("o6", "user", [{ type: "text", text: "好。" }], "2026-09-16T01:00:05.000Z", "o5"),
	];
	const orphanCaptured = { replay: [], prompt: undefined };
	const orphanCtx = makeCtx(tmp, {
		sessionManager: makeSessionManager(orphanEntries, "handoff-orphan"),
		getContextUsage: () => ({ tokens: 200_000, percent: 20, contextWindow: 1_000_000 }),
		modelRegistry: {
			hasConfiguredAuth: () => true,
			find: () => undefined,
			getApiKeyAndHeaders: async () => ({ ok: true, apiKey: "test-key" }),
			complete: async () => {
				throw new Error("the stub must serve the summary");
			},
		},
	});
	orphanCtx.newSession = captureNewSession(orphanCaptured);
	const stubsBefore = stubCalls.length;
	await runHandlers(pinPi, "session_start", orphanCtx);
	await pinPi.commands.get("auto-handoff").handler("now", orphanCtx);
	check("the orphan scenario still hands off", orphanCaptured.prompt !== undefined);
	check("the orphan result reaches the summary", stubCalls.slice(stubsBefore).some((call) => JSON.stringify(call.messages).includes("ORPHAN_SECRET")));
	check("the orphan cut keeps only the tail of the turn", !stubCalls.slice(stubsBefore).some((call) => JSON.stringify(call.messages).includes("继续改")));
	check("the orphan replay carries the kept tail", orphanCaptured.replay.map((message) => message.role).join(",") === "user,assistant,user");
	check("the orphan result never enters the replay", !JSON.stringify(orphanCaptured.replay).includes("ORPHAN_SECRET"));
	check("the orphan replay opens user-first", orphanCaptured.replay[0]?.role === "user" && orphanCaptured.replay[0]?.content?.[0]?.text === handoff.SPLIT_TURN_MARKER);

	// Session settings survive the switch and the pi session tree stays flat. Session files on
	// disk give the parent chain meaning: the replacement must point at the chain root, and the
	// staged settings must be keyed to the session that is being replaced.
	console.log("\n=== handoff session settings + tree flattening ===");
	const sessionDir = path.join(tmp, "sessions");
	await mkdir(sessionDir, { recursive: true });
	const sessionFile = (name) => path.join(sessionDir, `${name}.jsonl`);
	const writeHeader = async (file, id, parentSession) =>
		writeFile(file, `${JSON.stringify({ type: "session", version: 3, id, timestamp: "2026-09-17T00:00:00.000Z", cwd: tmp, ...(parentSession ? { parentSession } : {}) })}\n`);
	await writeHeader(sessionFile("root"), "root");
	await writeHeader(sessionFile("mid"), "mid", sessionFile("root"));
	await writeHeader(sessionFile("leaf"), "leaf", sessionFile("mid"));
	check("a session chain resolves to its root", (await handoff.resolveHandoffParentSession(sessionFile("leaf"))) === sessionFile("root"));
	check("a root session is its own parent", (await handoff.resolveHandoffParentSession(sessionFile("root"))) === sessionFile("root"));
	check("a missing session file is its own parent", (await handoff.resolveHandoffParentSession(sessionFile("nope"))) === sessionFile("nope"));
	check("an in-memory session has no parent", (await handoff.resolveHandoffParentSession(undefined)) === undefined);
	await writeHeader(sessionFile("cyc-a"), "cyc-a", sessionFile("cyc-b"));
	await writeHeader(sessionFile("cyc-b"), "cyc-b", sessionFile("cyc-a"));
	check("a parent cycle terminates", [sessionFile("cyc-a"), sessionFile("cyc-b")].includes(await handoff.resolveHandoffParentSession(sessionFile("cyc-a"))));
	// The header is the first line and is read to its newline, so an oversized one no longer costs
	// the whole ancestor walk (the old fixed 64KB read failed to parse and fell back to chaining).
	const oversized = JSON.stringify({ type: "session", version: 3, id: "big", timestamp: "2026-09-17T00:00:00.000Z", cwd: tmp, note: "x".repeat(80_000), parentSession: sessionFile("root") });
	await writeFile(sessionFile("big"), `${oversized}\n`);
	check("an oversized session header still resolves to its root", (await handoff.resolveHandoffParentSession(sessionFile("big"))) === sessionFile("root"));
	const pathological = JSON.stringify({ type: "session", version: 3, id: "huge", timestamp: "2026-09-17T00:00:00.000Z", cwd: tmp, note: "x".repeat(1_100_000), parentSession: sessionFile("root") });
	await writeFile(sessionFile("huge"), `${pathological}\n`);
	check("a header beyond the pathological cap falls back to chaining", (await handoff.resolveHandoffParentSession(sessionFile("huge"))) === sessionFile("huge"));
	// Exactly at the cap is still a header when the file ends there: the boundary is decided by one
	// extra byte, not by equality (`>` vs `>=` must not turn into a silent downgrade).
	const cap = 1024 * 1024;
	const headerFor = (note) => JSON.stringify({ type: "session", version: 3, id: "edge", timestamp: "2026-09-17T00:00:00.000Z", cwd: tmp, note, parentSession: sessionFile("root") });
	const exact = headerFor("x".repeat(cap - headerFor("").length));
	await writeFile(sessionFile("cap"), `${exact}\n`);
	check("a header exactly at the cap is still read", exact.length === cap && (await handoff.resolveHandoffParentSession(sessionFile("cap"))) === sessionFile("root"));

	const settingsEntries = [
		contentEntry("s1", "user", [{ type: "text", text: `Please carry the session settings over. ${'filler sentence. '.repeat(200)}` }], "2026-09-17T00:10:00.000Z"),
		contentEntry(
			"s2",
			"assistant",
			[{ type: "text", text: "Reading the current implementation first." }, { type: "toolCall", id: "sc1", name: "bash", arguments: { command: "cat settings.ts" } }],
			"2026-09-17T00:10:01.000Z",
			"s1",
		),
		toolResultEntry("s3", "sc1", "settings output line. ".repeat(60), "2026-09-17T00:10:02.000Z", "s2"),
		contentEntry("s4", "assistant", [{ type: "text", text: "Settings are read, carrying on." }], "2026-09-17T00:10:03.000Z", "s3"),
		contentEntry("s5", "user", [{ type: "text", text: "好，继续。" }], "2026-09-17T00:10:04.000Z", "s4"),
	];
	const settingsCtx = makeCtx(tmp, {
		sessionManager: { ...makeSessionManager(settingsEntries, "leaf"), getSessionFile: () => sessionFile("leaf") },
		getContextUsage: () => ({ tokens: 200_000, percent: 20, contextWindow: 1_000_000 }),
		thinkingLevel: "high",
		model: { provider: "deepseek", id: "deepseek-flash" },
		modelRegistry: {
			hasConfiguredAuth: () => true,
			find: () => undefined,
			getApiKeyAndHeaders: async () => ({ ok: true, apiKey: "test-key" }),
			complete: async () => {
				throw new Error("the stub must serve the summary");
			},
		},
	});
	const settingsCaptured = { parentSession: undefined, replay: [], prompt: undefined };
	settingsCtx.newSession = async (options) => {
		settingsCaptured.parentSession = options.parentSession;
		const replacement = makeSessionManager([], "settings-next");
		await options.setup(replacement);
		settingsCaptured.replay = replacement.entries.slice();
		const replacementCtx = makeCtx(tmp, { sessionManager: replacement });
		replacementCtx.sendUserMessage = (text) => {
			settingsCaptured.prompt = text;
		};
		await options.withSession(replacementCtx);
		return { cancelled: false };
	};
	await runHandlers(pinPi, "session_start", settingsCtx);
	await pinPi.commands.get("auto-handoff").handler("now", settingsCtx);

	const markerFile = handoff.handoffSettingsFile(tmp);
	const markerExists = () => readFile(markerFile, "utf8").then(() => true).catch(() => false);
	const staged = JSON.parse(await readFile(markerFile, "utf8").catch(() => "{}"));
	check("the handoff still continues in a fresh session", settingsCaptured.prompt !== undefined && settingsCaptured.replay.length > 0);
	check("the replacement is parented to the chain root", settingsCaptured.parentSession === sessionFile("root"));
	check(
		"the outgoing model and thinking level are staged",
		staged.model?.provider === "deepseek" && staged.model?.id === "deepseek-flash" && staged.thinkingLevel === "high",
	);
	check("the stage is keyed to the replaced session", staged.previousSessionFile === sessionFile("leaf") && typeof staged.at === "number");
	const memoryGitignore = await readFile(path.join(tmp, ".agents/memory/.gitignore"), "utf8").catch(() => "");
	check("the staged settings stay out of commits", memoryGitignore.includes(handoff.HANDOFF_SETTINGS_FILE));

	// pi builds the replacement from its own defaults, so the staged settings are applied from the
	// fresh extension instance's session_start (after the replay, before the continuation prompt).
	console.log("\n=== restoreHandoffSessionSettings ===");
	const restorePi = makePi({ cwd: tmp, thinkingLevel: "max" });
	await (await loadDefault(`${PC}/index.ts`, stubAlias))(restorePi);
	const restoredModel = { provider: "deepseek", id: "deepseek-flash", name: "deepseek flash" };
	const replacementCtx = makeCtx(tmp, {
		sessionManager: makeSessionManager([], "settings-next"),
		model: { provider: "deepseek", id: "deepseek-lite" },
		thinkingLevel: "max",
		modelRegistry: { hasConfiguredAuth: () => true, find: () => restoredModel, complete: async () => { throw new Error("no model call expected"); } },
	});
	await runHandlers(restorePi, "session_start", replacementCtx, { reason: "new", previousSessionFile: sessionFile("leaf") });
	check("the replacement switches to the outgoing model", restorePi.modelCalls[0] === restoredModel);
	check("the replacement takes the outgoing thinking level", restorePi.thinkingCalls.join(",") === "high");
	check("the staged settings are consumed by that one switch", !(await markerExists()));

	const stageFor = (overrides) =>
		handoff.stageHandoffSessionSettings(tmp, {
			previousSessionFile: sessionFile("leaf"),
			model: { provider: "deepseek", id: "deepseek-flash" },
			thinkingLevel: "high",
			at: Date.now(),
			...overrides,
		});
	const resetCalls = () => {
		restorePi.modelCalls.length = 0;
		restorePi.thinkingCalls.length = 0;
	};

	resetCalls();
	await stageFor({});
	await runHandlers(restorePi, "session_start", replacementCtx, { reason: "new", previousSessionFile: sessionFile("mid") });
	check("a different predecessor never inherits", restorePi.modelCalls.length === 0 && restorePi.thinkingCalls.length === 0);
	// Only that predecessor's successor can consume the stage, so anything else is a leftover (a
	// crash between staging and `newSession()`): it is dropped now instead of waiting for the TTL.
	check("a foreign switch drops the stage instead of keeping it", !(await markerExists()));

	resetCalls();
	await stageFor({ at: Date.now() - 11 * 60_000 });
	await runHandlers(restorePi, "session_start", replacementCtx, { reason: "new", previousSessionFile: sessionFile("leaf") });
	check("a stale stage is ignored", restorePi.modelCalls.length === 0 && restorePi.thinkingCalls.length === 0);
	check("a stale stage is cleaned up", !(await markerExists()));

	resetCalls();
	await stageFor({});
	await runHandlers(restorePi, "session_start", replacementCtx, { reason: "resume", previousSessionFile: sessionFile("leaf") });
	check("a resume is not the handoff successor", restorePi.modelCalls.length === 0 && restorePi.thinkingCalls.length === 0);
	check("a resume leaves the stage alone", await markerExists());

	resetCalls();
	await stageFor({ model: { provider: "deepseek", id: "deepseek-lite" }, thinkingLevel: "max" });
	await runHandlers(restorePi, "session_start", replacementCtx, { reason: "new", previousSessionFile: sessionFile("leaf") });
	check("settings that already match are left untouched", restorePi.modelCalls.length === 0 && restorePi.thinkingCalls.length === 0);
	check("matching settings are still consumed", !(await markerExists()));

	resetCalls();
	const ghostCtx = makeCtx(tmp, {		sessionManager: makeSessionManager([], "settings-next"),
		model: { provider: "deepseek", id: "deepseek-lite" },
		thinkingLevel: "max",
		modelRegistry: { hasConfiguredAuth: () => true, find: () => undefined, complete: async () => { throw new Error("no model call expected"); } },
	});
	await stageFor({ model: { provider: "ghost", id: "gone" }, thinkingLevel: "low" });
	await runHandlers(restorePi, "session_start", ghostCtx, { reason: "new", previousSessionFile: sessionFile("leaf") });
	check(
		"an unavailable model warns instead of breaking session start",
		ghostCtx.notifications.some(([message, type]) => type === "warning" && message.includes("ghost/gone")),
	);
	check("the thinking level still applies without the model", restorePi.thinkingCalls.join(",") === "low");

	resetCalls();
	const originalSetModel = restorePi.setModel;
	restorePi.setModel = async () => false;
	await stageFor({});
	await runHandlers(restorePi, "session_start", replacementCtx, { reason: "new", previousSessionFile: sessionFile("leaf") });
	check(
		"a refused model switch warns",
		replacementCtx.notifications.some(([message, type]) => type === "warning" && message.includes("no authentication")),
	);
	restorePi.setModel = originalSetModel;

	// The stage is private but transient, so a session_start that is not its successor must stop
	// before resolving the project root (which shells out to git).
	const quietCwd = path.join(tmp, "quiet-cwd");
	await mkdir(quietCwd, { recursive: true });
	const quietPi = makePi({ cwd: quietCwd });
	let quietExecs = 0;
	const quietExec = quietPi.exec;
	quietPi.exec = async (...execArgs) => {
		quietExecs += 1;
		return quietExec(...execArgs);
	};
	await stageFor({});
	await handoff.restoreHandoffSessionSettings(quietPi, makeCtx(quietCwd, { sessionManager: makeSessionManager([], "quiet") }), { reason: "resume", previousSessionFile: sessionFile("leaf") });
	check("a non-handoff session start stops before resolving the project root", quietExecs === 0);
	await handoff.clearHandoffSessionSettings(tmp);

	// A switch cancelled by another extension must not leave a stage behind for a later `/new`.
	const cancelCtx = makeCtx(tmp, {
		sessionManager: { ...makeSessionManager(settingsEntries, "leaf-2"), getSessionFile: () => sessionFile("leaf") },
		getContextUsage: () => ({ tokens: 200_000, percent: 20, contextWindow: 1_000_000 }),
		modelRegistry: pinCtx.modelRegistry,
	});
	cancelCtx.newSession = async () => ({ cancelled: true });
	await pinPi.commands.get("auto-handoff").handler("now", cancelCtx);
	check("a cancelled handoff clears its stage", !(await markerExists()));
	check("a cancelled handoff keeps the session", cancelCtx.notifications.some(([message]) => message.includes("cancelled by another extension")));

	// A switch that throws never produced a replacement either: the stage must be cleared too.
	const throwCtx = makeCtx(tmp, {
		sessionManager: { ...makeSessionManager(settingsEntries, "leaf-3"), getSessionFile: () => sessionFile("leaf") },
		getContextUsage: () => ({ tokens: 200_000, percent: 20, contextWindow: 1_000_000 }),
		modelRegistry: pinCtx.modelRegistry,
	});
	throwCtx.newSession = async () => {
		throw new Error("switch exploded");
	};
	await pinPi.commands.get("auto-handoff").handler("now", throwCtx);
	check("a failed switch clears its stage", !(await markerExists()));
	check(
		"a failed switch is reported to the user",
		throwCtx.notifications.some(([message, type]) => type === "error" && message.includes("Auto handoff failed")),
	);
} finally {
	delete globalThis.__handoffStub;
	await rm(tmp, { recursive: true, force: true });
}

console.log(failures === 0 ? "\nhandoff: all checks passed." : `\nhandoff: ${failures} check(s) failed.`);
process.exit(failures === 0 ? 0 : 1);
