import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { loadDefault, loadNamespace, makeCtx, makePi, makeSessionManager, messageEntry, PC, runHandlers } from "./harness.mjs";

/**
 * Handoff scaffolding tests: the continuation prompt follows the conversation language
 * (`auto`), an explicit `lang` config wins, and carried-over continuation prompts are replaced
 * by an omission marker in the verbatim replay slice.
 *
 * Known coverage gap (recorded, deliberately not pinned here): the `runHandoff` call sites —
 * `localizeSummaryHeadings` inside `generateHandoffSummary` and
 * `languageMessagesFor(olderMessages, carriedMessages)` — are covered only through their pure
 * functions, so a mutation at the call site keeps this file green (review round 5, F3/F5).
 * Pinning them needs an injectable summarizer plus a `newSession` mock in the harness.
 */

const tmp = await mkdtemp(path.join(os.tmpdir(), "pi-handoff-"));
let failures = 0;
function check(label, value) {
	console.log(`${value ? "OK  " : "FAIL"} ${label}`);
	if (!value) failures += 1;
}
const configPath = path.join(tmp, ".agents/memory/project-context.json");
const readConfig = () => readFile(configPath, "utf8").then((raw) => JSON.parse(raw)).catch(() => undefined);

try {
	await mkdir(path.join(tmp, ".agents/memory"), { recursive: true });

	const handoff = await loadNamespace(`${PC}/handoff.ts`);

	console.log("=== detectHandoffLanguage ===");
	check("Chinese user text picks zh", handoff.detectHandoffLanguage(["那做了呗，统一一下", "把记忆也改成 append-only 的模型，别残留隐患"]) === "zh");
	check("English user text picks en", handoff.detectHandoffLanguage(["fix the bug", "add tests for the replay slice"]) === "en");
	check("short Chinese sample falls back to en", handoff.detectHandoffLanguage(["B C A", "好"]) === "en");
	check(
		"Chinese prose dominates code-heavy samples",
		handoff.detectHandoffLanguage(["这段代码 memory.jsonl 的 fold 逻辑要按 mtime 判断外部编辑，不要每次重扫", "const value = await readJson(file);"]) === "zh",
	);

	console.log("\n=== buildHandoffPrompt ===");
	const base = {
		percent: 16,
		keptTokens: 20_000,
		guardWaiting: false,
		summaryWithIndex: "## Goal\n- 收尾。\n\n<read-files>\na.ts\n</read-files>",
		previousSessionId: "01a0a58e-7ef4-7763-95f3-5bcf04fdc388",
		previousSessionFile: "/home/user/.pi/agent/sessions/x.jsonl",
	};
	const zh = handoff.buildHandoffPrompt({ ...base, language: "zh" });
	check("zh preamble carries the percent", zh.startsWith("本会话接手上一会话（其上下文窗口已用 16%）。"));
	check("zh headings", zh.includes("## 交接摘要") && zh.includes("## 上一会话信息"));
	check("zh details", zh.includes("- 上一会话 id：01a0a58e") && zh.includes("- 原始记录（JSONL）：/home/user/.pi/agent/sessions/x.jsonl"));
	check("zh closing", zh.trimEnd().endsWith("从上次中断处继续。"));
	check("zh has no English scaffolding", !zh.includes("## Handoff Summary") && !zh.includes("Continue the task from where it left off."));

	const en = handoff.buildHandoffPrompt({ ...base, language: "en" });
	check(
		"en keeps the legacy shape",
		en.startsWith("This session continues work handed off from a previous session (16% of its context window had been used).") &&
			en.includes("## Handoff Summary") &&
			en.includes("## Previous session details") &&
			en.trimEnd().endsWith("Continue the task from where it left off."),
	);

	const zhSummaryOnly = handoff.buildHandoffPrompt({ ...base, language: "zh", keptTokens: 0 });
	check("zh summary-only carry line", zhSummaryOnly.includes("上一会话只留下下面的交接摘要"));

	const zhGuarded = handoff.buildHandoffPrompt({ ...base, language: "zh", guardWaiting: true, pendingQuestion: "选 1 还是 2？" });
	check("zh guarded prompt carries the question", zhGuarded.includes("## 待用户回答的问题") && zhGuarded.includes("选 1 还是 2？"));
	check("zh guarded prompt waits for the user", zhGuarded.trimEnd().endsWith("任务停在上面的问题上。不要替用户选选项或开工，等用户回答。"));
	check("guarded prompt notes the open decision", zhGuarded.includes("这个决定仍未决"));

	const noFile = handoff.buildHandoffPrompt({ ...base, language: "zh", previousSessionFile: undefined });
	check("no transcript line without a session file", !noFile.includes("原始记录"));
	check("zh unknown percent is localized", handoff.buildHandoffPrompt({ ...base, language: "zh", percent: null }).includes("已用 阈值以上）。"));
	check(
		"en unknown percent keeps the legacy wording",
		handoff.buildHandoffPrompt({ ...base, language: "en", percent: null }).startsWith("This session continues work handed off from a previous session (over threshold"),
	);

	console.log("\n=== isHandoffPromptText ===");
	// Literal text generated by the pre-language build (kept 01a0a58e's prompt shape).
	const legacy = [
		"This session continues work handed off from a previous session (16% of its context window had been used).",
		"The handoff summary below covers the earlier part of that session; its most recent messages were carried over verbatim.",
		"Verify the current state of files with tools before re-applying changes, and do not redo completed work.",
		"",
		"## Handoff Summary",
		"",
		"## Goal\n- 收尾。",
		"",
		"## Previous session details",
		"- Previous session id: 01a0a58e-7ef4-7763-95f3-5bcf04fdc388",
		"Continue the task from where it left off.",
	].join("\n");
	check("recognizes a generated zh prompt", handoff.isHandoffPromptText(zh));
	check("recognizes a generated en prompt", handoff.isHandoffPromptText(en));
	check("recognizes a legacy English prompt", handoff.isHandoffPromptText(legacy));
	check("ordinary user message is not a prompt", !handoff.isHandoffPromptText("那做了呗，统一一下"));
	check("assistant report is not a prompt", !handoff.isHandoffPromptText("## Goal\n- 收尾。"));
	check("a quote prefixed by the user is not a prompt", !handoff.isHandoffPromptText(`补，但是当前会话怎么出现了：\n${en}`));
	check("a quote with appended text is not a prompt", !handoff.isHandoffPromptText(`${en}\n\n顺便问一下，这个 HANDOFF.md 为什么没人看？`));
	check("a legacy quote with appended text is not a prompt", !handoff.isHandoffPromptText(`${legacy}\n另外把 v0.1.3 也处理一下`));
	check("headings alone are not a prompt", !handoff.isHandoffPromptText("## Handoff Summary\n\n没什么。"));
	check("empty text is not a prompt", !handoff.isHandoffPromptText("   "));

	console.log("\n=== replayMessagesFor ===");
	const entries = [
		messageEntry("e1", "user", "那做了呗，统一一下", "2026-09-16T00:41:39.660Z"),
		messageEntry("e2", "user", legacy, "2026-09-16T00:41:39.844Z"),
		messageEntry("e3", "assistant", "按交接要求先核对当前实际状态。", "2026-09-16T00:41:44.876Z"),
		messageEntry("e4", "toolResult", "=== HEAD ===\ne4d48c4", "2026-09-16T00:41:57.106Z"),
		messageEntry("e5", "user", zh, "2026-09-16T00:41:58.000Z"),
	];
	const kept = handoff.replayMessagesFor(entries);
	check("stale continuation prompts are replaced by the marker", kept.filter((message) => message.content?.[0]?.text === handoff.REPLAY_MARKER).length === 2);
	check("the raw prompt text never reaches the replay", !kept.some((message) => (message.content?.[0]?.text ?? "").includes("## Handoff Summary")));
	check("real conversation stays in the slice", kept.filter((message) => message.content?.[0]?.text !== handoff.REPLAY_MARKER).length === 3);

	console.log("\n=== replay block shape ===");
	// A slice that starts on a carried-over prompt used to be kept as-is (user-first); replacing
	// it must not make the block open with an assistant message, which some providers reject.
	const cutSlice = [
		messageEntry("c0", "user", legacy, "2026-09-16T00:41:00.000Z"),
		messageEntry("c1", "assistant", "按交接要求先核对当前实际状态。", "2026-09-16T00:41:01.000Z"),
		messageEntry("c2", "user", "真实用户问题", "2026-09-16T00:41:02.000Z"),
	];
	const replayed = handoff.replayMessagesFor(cutSlice);
	check("the replay block still opens with a user message", replayed[0]?.role === "user");
	check("the opening message is the omission marker", replayed[0]?.content?.[0]?.text === handoff.REPLAY_MARKER);
	check("later real messages are untouched", replayed[2]?.content?.[0]?.text === "真实用户问题");
	const plain = handoff.replayMessagesFor([messageEntry("q0", "user", "普通消息", "2026-09-16T00:42:00.000Z"), messageEntry("q1", "assistant", "普通回答", "2026-09-16T00:42:01.000Z")]);
	check("no prompt means no marker", !plain.some((message) => message.content?.[0]?.text === handoff.REPLAY_MARKER));

	console.log("\n=== buildHandoffDocument ===");
	const docParts = {
		previousSessionId: "01a0a7a9-7235-7763-95f3-5bdc121f5eff",
		projectRoot: "/tmp/proj",
		sessionLogRel: ".agents/memory/session-logs/01a0a7a9/session.md",
		summaryWithIndex: "## Goal\n- 收尾。",
		createdAt: "2026-09-16T00:50:03.901Z",
	};
	const zhDoc = handoff.buildHandoffDocument({ ...docParts, language: "zh" });
	check("zh document header", zhDoc.startsWith("# pi 会话 01a0a7a9-7235-7763-95f3-5bdc121f5eff 的交接文档") && zhDoc.includes("- 生成时间：2026-09-16T00:50:03.901Z"));
	check("zh document fields", zhDoc.includes("- 项目：/tmp/proj") && zhDoc.includes("- 会话日志：.agents/memory/session-logs/01a0a7a9/session.md") && zhDoc.includes("- 会话索引：.agents/memory/session-logs/INDEX.md"));
	check("document carries the summary", zhDoc.trimEnd().endsWith("- 收尾。"));
	const enDoc = handoff.buildHandoffDocument({ ...docParts, language: "en" });
	check(
		"en document keeps the legacy header",
		enDoc.startsWith("# Handoff from pi session 01a0a7a9-7235-7763-95f3-5bdc121f5eff") && enDoc.includes("- Created: 2026-09-16T00:50:03.901Z"),
	);

	console.log("\n=== resolveLanguage (auto) ===");
	const msg = (role, text) => ({ role, content: [{ type: "text", text }] });
	const englishTask = [msg("user", "please implement item 2 and run the tests"), msg("assistant", "done")];
	check(
		"injected prompts do not poison the language decision",
		handoff.resolveLanguage([msg("user", zh), ...englishTask], "auto") === "en",
	);
	check(
		"the user's own Chinese decides zh",
		handoff.resolveLanguage([msg("user", "那做了呗，统一一下"), ...englishTask], "auto") === "zh",
	);
	check(
		"recent messages win over older ones",
		handoff.resolveLanguage([msg("user", "这段中文很长很长，说明一开始说的是中文。"), ...[1, 2, 3, 4, 5, 6, 7, 8].map((index) => msg("user", `english follow-up number ${index}`))], "auto") === "en",
	);
	check(
		"a tiny recent sample falls back to the whole session",
		handoff.resolveLanguage([msg("user", "中文背景说明，包含足够多的汉字。"), msg("user", "ok")], "auto") === "zh",
	);
	check("explicit config wins", handoff.resolveLanguage(englishTask, "zh") === "zh" && handoff.resolveLanguage([msg("user", "中文")], "en") === "en");
	check(
		"the omission marker is ignored by language sampling",
		handoff.resolveLanguage([msg("user", zh), msg("user", handoff.REPLAY_MARKER)], "auto") === "zh",
	);
	// Pins the runHandoff wiring: the decision samples the raw carried slice, so the prompt sitting
	// on the cut point stays visible to the carry-forward rule (a marker-substituted slice hides it).
	check(
		"the raw slice feeds the language decision",
		handoff.resolveLanguage(handoff.languageMessagesFor([msg("user", "older english turn")], [msg("user", zh), msg("user", "ok")]), "auto") === "zh",
	);
	check("a short Chinese reply keeps zh", handoff.resolveLanguage([msg("user", zh), msg("user", "继续")], "auto") === "zh");
	check(
		"a single-character reply carries the language forward",
		handoff.resolveLanguage([msg("user", zh), msg("user", "好")], "auto") === "zh",
	);
	check(
		"an ASCII reply carries the language forward",
		handoff.resolveLanguage([msg("user", zh), msg("user", "ok")], "auto") === "zh" &&
			handoff.resolveLanguage([msg("user", en), msg("user", "ok")], "auto") === "en",
	);
	check(
		"substantive English still flips to en",
		handoff.resolveLanguage([msg("user", zh), msg("user", "please implement item 2 and run the tests")], "auto") === "en",
	);

	console.log("\n=== summary headings ===");
	// Verbatim headings from a real deepseek-flash summary captured during the TUI auto-handoff run
	// (2026-09-16): pi's EXACT-format prompt keeps the English template headings even when the
	// focus line asks for Chinese, so the fixed set is mapped deterministically.
	const realSummary = [
		"## Goal",
		"- 记录本次真机验证的相关要点（目标与检查点）。",
		"",
		"## Constraints & Preferences",
		"- 一切确认语句均使用一句话中文，且不要提问。",
		"",
		"## Progress",
		"### Done",
		"- [x] 记录第一条：本次真机验证的目标是 TUI 自动交臂。",
		"",
		"### In Progress",
		"- [ ] (无明确进行中的任务)",
		"",
		"### Blocked",
		"- (无)",
		"",
		"## Key Decisions",
		"- **概括方式统一**：两文件均以一句话中文概括。",
		"",
		"## Next Steps",
		"1. 等待用户后续指令。",
		"",
		"## Critical Context",
		"- 两次读取的 tool result 均有大段内容被截断。",
	].join("\n");
	const localized = handoff.localizeSummaryHeadings(realSummary, "zh");
	check(
		"zh maps every template heading",
		["## 目标", "## 约束与偏好", "## 进展", "### 已完成", "### 进行中", "### 受阻", "## 关键决策", "## 下一步", "## 关键上下文"].every((heading) =>
			localized.includes(heading),
		),
	);
	check(
		"zh leaves no template heading behind",
		!["## Goal", "## Constraints & Preferences", "## Progress", "### Done", "### In Progress", "### Blocked", "## Key Decisions", "## Next Steps", "## Critical Context"].some(
			(heading) => localized.includes(heading),
		),
	);
	check("zh keeps the summary body", localized.includes("- [x] 记录第一条：本次真机验证的目标是 TUI 自动交臂。"));
	check("a heading word inside a line is not rewritten", handoff.localizeSummaryHeadings("- 参见 ## Goal 一节", "zh") === "- 参见 ## Goal 一节");
	check("a heading inside a code fence is not rewritten", handoff.localizeSummaryHeadings("```md\n## Goal\n```\n## Progress", "zh") === "```md\n## Goal\n```\n## 进展");
	check(
		"fences close with their own marker",
		handoff.localizeSummaryHeadings("~~~\n## Goal\n~~~\n## Goal", "zh") === "~~~\n## Goal\n~~~\n## 目标",
	);
	check("an indented heading keeps its indent", handoff.localizeSummaryHeadings("  ## Goal\n- x", "zh") === "  ## 目标\n- x");
	check("already localized headings are left alone", handoff.localizeSummaryHeadings("## 目标\n- x", "zh") === "## 目标\n- x");
	check(
		"en maps the localized headings back",
		handoff.localizeSummaryHeadings("## 目标\n### 已完成\n- x", "en") === "## Goal\n### Done\n- x",
	);
	check(
		"en also maps the variants real models produced",
		handoff.localizeSummaryHeadings("## 进度\n### 阻塞", "en") === "## Progress\n### Blocked",
	);

	console.log("\n=== config parsing ===");
	const parseConfig = async (raw) => {
		await writeFile(configPath, JSON.stringify(raw));
		return (await loadNamespace(`${PC}/config.ts`)).getConfig(tmp);
	};
	const flat = await parseConfig({ handoffLanguage: "zh" });
	check("flat handoffLanguage loads", flat.handoffLanguage === "zh");
	const flatWins = await parseConfig({ handoffLanguage: "zh", handoff: { language: "en" } });
	check("flat value beats the nested legacy key", flatWins.handoffLanguage === "zh");
	const nestedInvalid = await parseConfig({ handoff: { language: "fr" } });
	check("invalid nested value falls back to auto", nestedInvalid.handoffLanguage === "auto");
	const nested = await parseConfig({ handoff: { language: "en" } });
	check("nested legacy handoff.language loads", nested.handoffLanguage === "en");
	const invalid = await parseConfig({ handoffLanguage: "fr" });
	check("unknown language falls back to auto", invalid.handoffLanguage === "auto");
	const defaults = await parseConfig({});
	check("defaults to auto", defaults.handoffLanguage === "auto");
	// Legacy global file (`~/.pi/agent/auto-handoff.json`); redirect the agent dir instead.
	const agentDir = path.join(tmp, "agentdir");
	await mkdir(agentDir, { recursive: true });
	await writeFile(path.join(agentDir, "auto-handoff.json"), JSON.stringify({ language: "en" }));
	const previousAgentDir = process.env.PI_CODING_AGENT_DIR;
	process.env.PI_CODING_AGENT_DIR = agentDir;
	try {
		await writeFile(configPath, JSON.stringify({}));
		const globalLegacy = await (await loadNamespace(`${PC}/config.ts`)).getConfig(tmp);
		check("global legacy language loads", globalLegacy.handoffLanguage === "en");
	} finally {
		if (previousAgentDir === undefined) delete process.env.PI_CODING_AGENT_DIR;
		else process.env.PI_CODING_AGENT_DIR = previousAgentDir;
	}

	console.log("\n=== /auto-handoff lang ===");
	await writeFile(configPath, JSON.stringify({}));
	const pi = makePi({ cwd: tmp });
	await (await loadDefault(`${PC}/index.ts`))(pi);
	const ctx = makeCtx(tmp, { sessionManager: makeSessionManager([], "handoff-lang") });
	await runHandlers(pi, "session_start", ctx);
	const command = pi.commands.get("auto-handoff");
	check("command registered", command !== undefined);
	await command.handler("lang zh", ctx);
	check("lang zh persists", (await readConfig())?.handoffLanguage === "zh");
	await command.handler("lang fr", ctx);
	check("invalid language warns and leaves the config", (await readConfig())?.handoffLanguage === "zh" && String(ctx.notifications.at(-1)?.[0] ?? "").includes("lang auto|zh|en"));
	await command.handler("lang auto", ctx);
	check("lang auto persists", (await readConfig())?.handoffLanguage === "auto");
	await command.handler("language zh", ctx);
	check("the language alias works", (await readConfig())?.handoffLanguage === "zh");
	await command.handler("lang EN", ctx);
	check("the language value is case-insensitive", (await readConfig())?.handoffLanguage === "en");
	await command.handler("lang", ctx);
	check("a missing value warns and leaves the config", (await readConfig())?.handoffLanguage === "en" && String(ctx.notifications.at(-1)?.[0] ?? "").includes("lang auto|zh|en"));
	await command.handler("lang auto", ctx);
	await command.handler("status", ctx);
	check("status reports the language", String(ctx.notifications.at(-1)?.[0] ?? "").includes("lang auto"));

	console.log("\n=== /auto-handoff now (nothing to hand off) ===");
	// A no-op handoff must explain itself: both bail-outs used to return without any notify.
	await writeFile(configPath, JSON.stringify({ handoffKeepTokens: 50 }));
	const quiet = makePi({ cwd: tmp });
	await (await loadDefault(`${PC}/index.ts`))(quiet);
	const emptyCtx = makeCtx(tmp, { sessionManager: makeSessionManager([], "handoff-empty") });
	await runHandlers(quiet, "session_start", emptyCtx);
	await quiet.commands.get("auto-handoff").handler("now", emptyCtx);
	check(
		"an empty session reports the skip",
		String(emptyCtx.notifications.at(-1)?.[0] ?? "").includes("no messages yet") &&
			String(emptyCtx.notifications.at(-1)?.[1] ?? "") === "warning",
	);

	const short = makeSessionManager(
		[
			messageEntry("m1", "user", "你好", "2026-09-16T00:00:00.000Z"),
			messageEntry("m2", "assistant", "你好", "2026-09-16T00:00:01.000Z"),
		],
		"handoff-short",
	);
	const shortCtx = makeCtx(tmp, { sessionManager: short });
	await runHandlers(quiet, "session_start", shortCtx);
	await quiet.commands.get("auto-handoff").handler("now", shortCtx);
	check(
		"a session inside the keep window reports the skip",
		String(shortCtx.notifications.at(-1)?.[0] ?? "").includes("nothing older than the recent window") &&
			String(shortCtx.notifications.at(-1)?.[1] ?? "") === "warning",
	);

	console.log("\n=== auto trigger backoff ===");
	// maybeTrigger fires on every settle; a skip that keeps firing would warn on each turn.
	// The adaptive threshold needs the session to hold more than `handoffTargetTokens` of
	// conversation, so the mocked context carries real bulk instead of a huge baseline.
	await writeFile(configPath, JSON.stringify({ handoffEnabled: true, handoffKeepTokens: 50, handoffTargetTokens: 8_000, autoConsolidate: false }));
	const auto = makePi({ cwd: tmp });
	await (await loadDefault(`${PC}/index.ts`))(auto);
	const filler = "documentation line repeated to give the session real context weight. ".repeat(700);
	// buildContextEntries walks the parent chain from the leaf, so the mock entries must link.
	const firstTurn = messageEntry("a1", "user", filler, "2026-09-16T00:00:00.000Z");
	const secondTurn = messageEntry("a2", "assistant", "已收到。", "2026-09-16T00:00:01.000Z");
	secondTurn.parentId = firstTurn.id;
	const autoCtx = makeCtx(tmp, {
		sessionManager: makeSessionManager([firstTurn, secondTurn], "handoff-auto"),
		mode: "tui",
		getContextUsage: () => ({ tokens: 200_000, percent: 20, contextWindow: 1_000_000 }),
	});
	await runHandlers(auto, "session_start", autoCtx);
	await runHandlers(auto, "agent_settled", autoCtx);
	await new Promise((resolve) => setTimeout(resolve, 20));
	check("the threshold triggers the scheduled handoff", auto.sentMessages.includes("/auto-handoff force-auto"));
	await auto.commands.get("auto-handoff").handler("force-auto", autoCtx);
	check("the scheduled handoff explains the skip", String(autoCtx.notifications.at(-1)?.[0] ?? "").includes("nothing older than the recent window"));
	await runHandlers(auto, "agent_settled", autoCtx);
	await new Promise((resolve) => setTimeout(resolve, 20));
	check("a skipped auto handoff backs off instead of retrying every settle", auto.sentMessages.length === 1);
} finally {
	await rm(tmp, { recursive: true, force: true });
}

console.log(failures === 0 ? "\nhandoff: all checks passed." : `\nhandoff: ${failures} check(s) failed.`);
process.exit(failures === 0 ? 0 : 1);
